# Generated by Django 4.1.5 on 2024-03-09 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0002_remove_ad_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ['body'], 'verbose_name': 'Ad', 'verbose_name_plural': 'Ads'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['body'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
    ]
