# Generated by Django 4.2.7 on 2024-03-08 19:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid full_name",
                                message="only characters are allowed ",
                                regex="(^[A-Za-z]{3,16})([ ]{0,1})([A-Za-z]{3,45})?([ ]{0,1})?([A-Za-z]{3,25})?([ ]{0,1})?([A-Za-z]{3,15})",
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("de_activate_date", models.DateTimeField(blank=True, null=True)),
                ("registered_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "ordering": ["email"],
            },
        ),
        migrations.CreateModel(
            name="DeletedUsers",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounts.user",),
        ),
    ]
